# Generated by Django 5.0.1 on 2024-01-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='salary',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
